version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing dependencies...
      - apt-get update -y
      - apt-get install maven -y

  build:
    commands:
      - echo Building the WAR project...
      - mvn clean package -DskipTests
      - ls target/
      - mv target/SimpleAWSApp.war app.war

  post_build:
    commands:
      - echo Build complete.
      - mkdir -p deploy_bundle
      - cp app.war deploy_bundle/
      - cp appspec.yml deploy_bundle/
      - cp -r scripts deploy_bundle/
      - cd deploy_bundle
      - zip -r ../sp_artifact.zip .
      - cd ..

artifacts:
  files:
    - sp_artifact.zip
  discard-paths: yes
